# Importing and preparing supermarkets data

## Libraries and settings

In [1]:
# Libraries
import os
import fnmatch
import pandas as pd

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Get current working directory
print('Current working directory:', os.getcwd())

# Show .json files in the current working directory
flist = fnmatch.filter(os.listdir('.'), '*.json')
for i in flist:
    print(i)

Current working directory: /workspaces/data_analytics/Week_02
supermarkets.json

## Importing data

In [2]:
# Read the data to a pandas data frame
df1 = pd.read_json('supermarkets.json', encoding='utf-8')
df1.head(5)

,type,id,lat,lon,tags
0,node,33126515,47.155616,9.037915,"{'brand': 'Spar', 'brand:wikidata': 'Q610492',..."
1,node,36726161,47.226191,8.980329,"{'addr:city': 'Uznach', 'addr:housenumber': '2..."
2,node,39768209,47.225069,8.969981,"{'addr:city': 'Uznach', 'addr:postcode': '8730..."
3,node,39947904,47.376732,8.542161,"{'addr:city': 'Zürich', 'addr:country': 'CH', ..."
4,node,48932835,47.375020,8.522895,"{'addr:city': 'Zürich', 'addr:housenumber': '7..."

## Count number of rows and columns in the data frame

In [3]:
# Dimension (rows, columns)
print('Dimension:', df1.shape)

# Number of rows
print('Number of rows:', df1.shape[0])

# Number of columns
print('Number of columns:', df1.shape[1])

Dimension: (3392, 5)
Number of rows: 3392
Number of columns: 5

## Column 'tags' is a pandas Series with dictionaries -> change to data frame

In [4]:
# Type of the first item of column tags
print(type(df1.tags))
print(type(df1.tags[0]))

# Content of the first item of column tags
print(df1.tags[0].keys())

# Change to data frame
df2 = pd.DataFrame.from_records(df1.tags)
df2 = df2[['brand', 'shop', 'addr:city', 'addr:street', 'addr:housenumber', 'addr:postcode']]

# Rename selected columns
df2 = df2.rename(columns={'addr:city': 'city',
                          'addr:street':'street',
                          'addr:housenumber': 'housenumber',
                          'addr:postcode': 'postcode'})

# Show first records of data frame
df2.head()

<class 'pandas.core.series.Series'>
<class 'dict'>
dict_keys(['brand', 'brand:wikidata', 'brand:wikipedia', 'name', 'opening_hours', 'shop'])

    brand         shop    city          street housenumber postcode
0    Spar  supermarket     NaN             NaN         NaN      NaN
1  Migros  supermarket  Uznach  Zürcherstrasse          25     8730
2    Coop  supermarket  Uznach             NaN         NaN     8730
3    Coop  supermarket  Zürich   Bahnhofbrücke           1     8001
4  Migros  supermarket  Zürich    Wengistrasse           7     8004

## Merge df1 and df2

In [5]:
# Merge df and df2
df = pd.merge(df1[['type', 'id', 'lat', 'lon']], 
              df2[['brand', 'shop', 'city', 'street', 'housenumber', 'postcode']],
              left_index=True, 
              right_index=True)
df.head(5)

,type,id,lat,lon,brand,shop,city,street,housenumber,postcode
0,node,33126515,47.155616,9.037915,Spar,supermarket,NaN,NaN,NaN,NaN
1,node,36726161,47.226191,8.980329,Migros,supermarket,Uznach,Zürcherstrasse,25,8730
2,node,39768209,47.225069,8.969981,Coop,supermarket,Uznach,NaN,NaN,8730
3,node,39947904,47.376732,8.542161,Coop,supermarket,Zürich,Bahnhofbrücke,1,8001
4,node,48932835,47.375020,8.522895,Migros,supermarket,Zürich,Wengistrasse,7,8004

## Count and identify the number of missing values (if any)

In [6]:
# Count missing values
print(pd.isna(df).sum())

# Identify rows with missing values, e.g.:
df.loc[pd.isna(df['city'])]

type              0
id                0
lat               0
lon               0
brand          1065
shop              0
city           1777
street         1608
housenumber    1680
postcode       1709
dtype: int64

,type,id,lat,lon,brand,shop,city,street,housenumber,postcode
0,node,33126515,47.155616,9.037915,Spar,supermarket,NaN,NaN,NaN,NaN
5,node,60271452,47.406671,9.305450,NaN,supermarket,NaN,NaN,NaN,NaN
6,node,70656485,47.491253,8.733981,NaN,supermarket,NaN,NaN,NaN,NaN
10,node,81321513,47.532917,9.066408,Landi,supermarket,NaN,NaN,NaN,NaN
13,node,95582038,47.050385,9.059214,NaN,supermarket,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
3384,node,11083317088,46.862184,9.531169,Lidl,supermarket,NaN,NaN,NaN,NaN
3386,node,11098091830,46.205111,6.130174,Coop,supermarket,NaN,NaN,NaN,NaN
3387,node,11099817248,46.928691,7.561873,NaN,supermarket,NaN,NaN,NaN,NaN
3388,node,11103235832,46.166742,8.771970,Migros,supermarket,NaN,NaN,NaN,NaN
3391,node,11129298207,47.537518,7.608581,Coop,supermarket,NaN,NaN,NaN,NaN

## Count and identify duplicated values (if any)

In [7]:
# Count duplicated values
print(df.duplicated().sum())

# Identify rows with duplicated values, e.g.:
df[df[['id']].duplicated()]

0

Empty DataFrame
Columns: [type, id, lat, lon, brand, shop, city, street, housenumber, postcode]
Index: []

## Get data types of all variables

In [8]:
# Get data types (note that in pandas, a string is referred to as 'object')
df.dtypes

type            object
id               int64
lat            float64
lon            float64
brand           object
shop            object
city            object
street          object
housenumber     object
postcode        object
dtype: object

Additioal Filter

In [13]:
df_filtered = df.loc[(df['brand'] == 'Coop') & (df['city'] == 'Zürich')]
df_filtered

,type,id,lat,lon,brand,shop,city,street,housenumber,postcode
3,node,39947904,47.376732,8.542161,Coop,supermarket,Zürich,Bahnhofbrücke,1,8001
9,node,79977755,47.340070,8.530546,Coop,supermarket,Zürich,Alte Kalchbühlstrasse,15,8038
59,node,265776668,47.376417,8.559594,Coop,supermarket,Zürich,Zürichbergstrasse,75,8044
63,node,266630559,47.377716,8.511219,Coop,supermarket,Zürich,Badenerstrasse,333,8003
70,node,267345511,47.385809,8.516574,Coop,supermarket,Zürich,Maagplatz,1,8005
72,node,267468996,47.364872,8.521006,Coop,supermarket,Zürich,Uetlibergstrasse,20,8045
75,node,268603429,47.367360,8.546174,Coop,supermarket,Zürich,Theaterstrasse,18,8001
81,node,270692983,47.357940,8.554646,Coop,supermarket,Zürich,Seefeldstrasse,123,8008
84,node,271028686,47.366773,8.548079,Coop,supermarket,Zürich,Stadelhoferstrasse,10,8001
86,node,271029581,47.364300,8.555129,Coop,supermarket,Zürich,Forchstrasse,4,8008
96,node,276363821,47.418888,8.505699,Coop,supermarket,Zürich,Wehntalerstrasse,549,8046
121,node,283103824,47.393648,8.529543,Coop,supermarket,Zürich,Scheffelstrasse,12,8037
122,node,283126967,47.392539,8.524557,Coop,supermarket,Zürich,Röschibachstrasse,22,8037
209,node,313026968,47.375801,8.517445,Coop,supermarket,Zürich,Badenerstrasse,244,8004
225,node,321361788,47.395725,8.540471,Coop,supermarket,Zürich,Milchbuckstrasse,1-5,8057
446,node,470217716,47.384789,8.527125,Coop,supermarket,Zürich,Röntgenstrasse,48,8005
579,node,614828024,47.403421,8.589360,Coop,supermarket,Zürich,Hirzenbachstrasse,40,8051
623,node,651273252,47.373288,8.530562,Coop,supermarket,Zürich,Badenerstrasse,15,8004
630,node,659862626,47.375896,8.487025,Coop,supermarket,Zürich,Albisriederstrasse,334,8047
719,node,766705800,47.413421,8.540576,Coop,supermarket,Zürich,Sophie-Taeuber-Strasse,4,8050
892,node,1027136881,47.425628,8.496976,Coop,supermarket,Zürich,Mühlackerstrasse,199,8046
1240,node,1756956245,47.370252,8.537156,Coop,supermarket,Zürich,Bärengasse,16,8001
1314,node,1925758931,47.370793,8.515856,Coop,supermarket,Zürich,Birmensdorferstrasse,200,8003
1453,node,2264702137,47.387410,8.488921,Coop,supermarket,Zürich,Badenerstrasse,650,8048
1478,node,2323174782,47.377731,8.534719,Coop,supermarket,Zürich,Europaallee,5,8004
1722,node,2984223833,47.386247,8.499478,Coop,supermarket,Zürich,Baslerstrasse,50,8048
1918,node,3653968759,47.391114,8.508187,Coop,supermarket,Zürich,Pfingstweidstrasse,106,8005
2122,node,4328291097,47.347186,8.533072,Coop,supermarket,Zürich,Seestrasse,339,8038
2177,node,4424679510,47.377825,8.538369,Coop,supermarket,Zürich,NaN,NaN,8001
2194,node,4466482789,47.380692,8.534890,Coop,supermarket,Zürich,Zollstrasse,42,8005
2304,node,4848816876,47.372928,8.537713,Coop,supermarket,Zürich,Bahnhofstrasse,57,8001
2319,node,4896104281,47.357474,8.523064,Coop,supermarket,Zürich,Kalanderplatz,1,8045
2320,node,4896104282,47.389834,8.471856,Coop,supermarket,Zürich,Am Suteracher,14,8048
2321,node,4896104283,47.410477,8.546741,Coop,supermarket,Zürich,Wallisellenstrasse,1,8050
2563,node,6011935004,47.412872,8.547012,Coop,supermarket,Zürich,Andreasstrasse,5,8050
3007,node,8541239873,47.387455,8.517340,Coop,supermarket,Zürich,Maschinenstrasse,10,8005
3338,node,10711459945,47.369962,8.509175,Coop,supermarket,Zürich,Birmensdorferstrasse,310,8055

In [ ]:
#isana = pd.isna(df_filtered).sum()

### Save data to file

In [9]:
df.to_csv('supermarkets_data_prepared.csv', 
          sep=",", 
          encoding='utf-8',
          index=False)

### Jupyter notebook --footer info-- (please always provide this at the end of each submitted notebook)

In [10]:
import os
import platform
import socket
from platform import python_version
from datetime import datetime

print('-----------------------------------')
print(os.name.upper())
print(platform.system(), '|', platform.release())
print('Datetime:', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print('Python Version:', python_version())
print('-----------------------------------')

-----------------------------------
POSIX
Linux | 6.8.0-1014-azure
Datetime: 2024-09-25 13:31:58
Python Version: 3.11.10
-----------------------------------